// This file is part of the course TPV2@UCM - Samir Genaim


#pragma once

// Components list - must have at least one element
//
#define _CMPS_LIST_ \
	TRANSFORM,\
	IMAGE,\
	DESTROYONBORDER,\
	IMAGEWITHFRAMES,\
	WEAPONIMAGE,\
	MOVEMENTCTRL, \
	ENTITYCMP, \
	ENTITYSTAT, \
	VECTOR2D, \
	STATUSEFFECT, \
	ANIMATORCOMPONENT, \
	PLAYERCTRL, \
	PLAYERANIMCMP, \
	GAMECTRL, \
	BULLETSTATS, \
	BUTTON, \
	GHOSTTPCMP, \
	GHOSTATKCMP, \
	GHOSTAICMP, \
    SLIMEMOVCMP, \
    SLIMEATKCMP, \
    SLIMESTATCMP, \
    SLIMEVECCMP, \
	SLIMEANIMCMP, \
    UNDEADMOVCMP, \
    UNDEADATKCMP, \
    UNDEADSTATCMP, \
    UNDEADVECCMP,\
	UNDEADANIMCMP,\
	MINIGAMEGENERATORCMP, \
	TIMERRENDERERCMP, \
	HOMINGCOMPONENT, \
	TILECOLLISIONCHECKER, \
	MOVETHROUGHROOMS, \
	ARMORMOVCMP, \
	ARMORATKCMP, \
	ARMORSTATCMP, \
	ARMORVECCMP, \
	ARMORCOLCMP, \
	ARMORANIMCMP, \
    BOSSVECCMP, \
	BOSSATKCMP, \
	BOSSSTATCMP, \
	BOSSMOVCMP, \
    BOSSCOLCMP,\
    NECROVECCMP,\
    NECROMOVCMP,\
    NECROCRTCMP,\
    NECROSTATCMP,\
    SPAWNCMP,\
	PICKABLECMP,\
    STATCMP,\
    SPAWNSTATCMP,\
    SPAWNMOVCMP,\
    ENEMYHOMING,\
    ENEMYHITTED, \
	HEALTHBAR
 




// Groups list - must have at least one element
//
#define _GRPS_LIST_ \
	BULLET,\
	ENEMYBULLET,\
    ENEMY,\
	UPGRRADE

// Handlers list - must have at least one element
//
#define _HDLRS_LIST_ \
    PLAYER, \
	GAMEINFO

