// This file is part of the course TPV2@UCM - Samir Genaim


#pragma once

// Components list - must have at least one element
//
#define _CMPS_LIST_ \
	TRANSFORM,\
	IMAGE,\
	DESTROYONBORDER,\
	IMAGEWITHFRAMES,\
	WEAPONIMAGE,\
	MOVEMENTCTRL,\
	ENTITYCMP,\
	ENTITYSTAT,\
	VECTOR2D,\
	STATUSEFFECT,\
	PLAYERCTRL,\
	PLAYERANIMCOMPONENT,\
	GAMECTRL,\
	GHOSTCMP,\
	BULLETSTATS,\
	BUTTON,\
    SLIMEMOVCMP,\
    SLIMEATKCMP,\
    SLIMESTATCMP,\
    SLIMEVECCMP,\
    UNDEADMOVCMP,\
    UNDEADATKCMP,\
    UNDEADSTATCMP,\
    UNDEADVECCMP,\
	MINIGAMEGENERATORCMP,\
	TIMERRENDERERCMP,\
	HOMINGCOMPONENT,\
	TILECOLLISIONCHECKER,\
	MOVETHROUGHROOMS,\
	ARMORMOVCMP,\
	ARMORATKCMP,\
	ARMORSTATCMP,\
	ARMORVECCMP,\
	ARMORCOLCMP,\
    BOSSVECCMP,\
	BOSSATKCMP,\
	BOSSSTATCMP,\
	BOSSMOVCMP,\
    BOSSCOLCMP,\
    NECROVECCMP,\
    NECROMOVCMP,\
    NECROCRTCMP,\
    NECROSTATCMP,\
    SPAWNCMP,\
	PICKABLECMP,\
    STATCMP,\
    SPAWNSTATCMP,\
    SPAWNMOVCMP,\
    ENEMYHOMING
 




// Groups list - must have at least one element
//
#define _GRPS_LIST_ \
	BULLET,\
	ENEMYBULLET,\
    ENEMY
// Handlers list - must have at least one element
//
#define _HDLRS_LIST_ \
    PLAYER, \
	GAMEINFO

